### ISSUE TITLE
Deprecated minimatch 2.0.10 will require to use fileset-2.0.2

### ISSUE THREAD

**Issue by ashl1** [istanbuljs/istanbul-api#6]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

```
│ ├─┬ istanbul-api@1.1.0-alpha.1 
│ │ ├─┬ fileset@0.2.1 
│ │ │ ├── glob@5.0.15 
│ │ │ └── minimatch@2.0.10 
```

While [fileset-2.0.2](https://github.com/mklabs/node-fileset/blob/v2.0.2/package.json) use appropriate minimatch-3.0.2

**Comment by benediktvaldez** [comment]
Came here because of this yarn output

``` shell
warning jest > jest-cli > istanbul-api > fileset > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```

This is literally the only warning I get in my setup and I'd love it to be done – is there anything that needs to be done beyond fixing the test to merge #7 ? According to @lukyth the tests were broken even before this change.

What can I do to help? 😄
